### ISSUE TITLE
Authentication failure when not running as root

### ISSUE THREAD

**Issue by Thorarin** [CamW/npam#1]
I was glad to find this nice little library on NuGet 😄 

Unfortunately I seem to be unable to authenticate in my application (.NET Core 2.1 running on Debian) when running as a user other than root. Does my process need to be given permission to use PAM or that particular service name in some way, or is root really required?

/var/log/auth.log shows little information on faiiled authentication:
```
dotnet: pam_unix(servicename:auth): authentication failure; logname= uid=33 euid=33
    tty= ruser= rhost=  user=marcel
```

Calls to `NpamUser.GetAccountInfo(...)` seem to work correctly when my process is not running as root.

**Comment by CamW** [comment]
I believe that this is due to pam_authenticate needing access to /etc/shadow. By default that's restricted because it would be a security concern if it weren't. One option would be to apply a [setuid](https://en.wikipedia.org/wiki/Setuid) access right to your executable. Using root or even better, a new user which has access to /etc/shadow to limit exposure as far as possible.
Needless to say, care should be taken. Specifically to avoid brute forcing /etc/shadow through the new executable.

**Comment by Thorarin** [comment]
Thanks, that is also what I read late last night. Too bad, but creating a user in the shadow group should be acceptable for my purpose.
